debug pages

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -55,6 +55,16 @@ jobs:
           allure_history: allure-history
           allure_results: allure-results
 
+      
+      - name: Debug publish directory
+        run: ls -R gh-pages/allure-history || echo "Directory not found or empty"
+
+      # Clean and prepare gh-pages directory
+      - name: Clean up gh-pages directory
+        run: |
+          rm -rf gh-pages/*
+          mkdir -p gh-pages
+      
       - name: Publish Allure report to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         if: always()
